export const ADD_PRESENTATION = 'ADD_PRESENTATION';
export const EDIT_PRESENTATION = 'EDIT_PRESENTATION';

export const ADD_EDUCATION = 'ADD_EDUCATION';
export const EDIT_EDUCATION = 'EDIT_EDUCATION';

export const ADD_EXPERIENCE = 'ADD_EXPERIENCE';
export const EDIT_EXPERIENCE = 'EDIT_EXPERIENCE';